---
# tasks file for nodos_kubernetes-role
- name: Módulo Br_netfilter presente 
  modprobe:
    name: br_netfilter
    state: present
- name: Transparent Masquerading
  firewalld:
    masquerade: yes
    permanent: yes
    state: enabled
- name: Reiniciado firewall
  systemd:
    name: firewalld
    state: reloaded
- name: presente /etc/sysctl.d/k8s.conf
  copy:
    dest: /etc/sysctl.d/k8s.conf
    mode: u=rwx,g=rwx,o=rwx
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
  notify: Recarga conf sistema
- name: desactivando swap
  shell: "{{ item }}"
  with_items:
    - swapoff -a 
    - sed -i '/swap/d' /etc/fstab
- name: repos Centos
  get_url:
    url: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{OS}}/devel:kubic:libcontainers:stable.repo"
    dest: "/etc/yum.repos.d/devel:kubic:libcontainers:stable.repo"
  register: repo_output_centos  
- name: repos cri-o
  get_url:
    url: "https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:{{VERSION}}/{{OS}}/devel:kubic:libcontainers:stable:cri-o:{{VERSION}}.repo"
    dest: "/etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:{{VERSION}}.repo"
  register: repo_output_cri_o
- debug:
    msg: 
      - "respuesta Repos Centos: {{repo_output_centos.msg}}"
      - "respuesta Repos Cri-o: {{repo_output_cri_o.msg}}"
- name: Instalado y actualizado Cri-o
  dnf:
    name: cri-o
    state: latest
- name: presente /etc/modules-load.d/crio.conf
  copy:
    dest: /etc/modules-load.d/crio.conf
    mode: u=rwx,g=rwx,o=rwx
    content: |
      overlay
      br_netfilter
- name: servicio cri-o activo y habilitado
  service:
    name: crio
    state: started
    enabled: yes
- name: Configurado /etc/yum.repos.d/kubernetes.repo
  copy:
    dest: /etc/yum.repos.d/kubernetes.repo
    mode: u=rwx,g=rwx,o=rwx
    content: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
      enabled=1
      gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      exclude=kubelet kubeadm kubectl
- name: Instalado kubernetes
  dnf:
    name: "{{ item }}"
    state: installed
    disable_excludes: kubernetes
  with_items:
  - kubelet
  - kubeadm
  - kubectl
- name: servicio kubelet activo y habilitado
  service:
    name: kubelet
    state: started
    enabled: yes